### ISSUE TITLE
ssl cert expired

### ISSUE THREAD

**Issue by jlopp** [PierreRochard/bitcoin-acks#105]
I suggest you look into setting up certbot to autorenew your letsencrypt certs; it doesn't take much effort to get the daemon running.

**Comment by jlopp** [comment]
*bump* looks like it expired again

**Comment by pinheadmz** [comment]
expired again!

**Comment by jlopp** [comment]
bump bump bump

**Comment by jlopp** [comment]
fixed again... see you next year? 😄
