### ISSUE TITLE
Be able to filter by ACK type

### ISSUE THREAD

**Issue by achow101** [PierreRochard/bitcoin-acks#108]
Currently there's no way to filter reviews by ACK type, all ACK types are bundled together. As a maintainer, I would find it more useful to be able to ignore PRs that only have e.g. Stale ACKs, or do not have some number of current Tested ACKs.

**Comment by PierreRochard** [comment]
Fixed, added various counts to filter on 
<img width="258" alt="image" src="https://user-images.githubusercontent.com/6299681/204114972-b549919c-c143-4e09-9705-dd65dcc9b033.png">
