### ISSUE TITLE
Sorting by most recently updated seems broken

### ISSUE THREAD

**Issue by ryanofsky** [PierreRochard/bitcoin-acks#17]
Nice job with this. Site is great! 

I noticed if I click "updated" column header in order to see the most recently updated PR's, the resulting sort order seems kind of random. Would be nice if this worked, since I often use "sort:updated-desc" term in github to check active prs.

**Comment by PierreRochard** [comment]
Thank you!

I think the randomness you're seeing is the distinction between the pinned high priority PRs and the rest. If something else is up I'd need a URL and/or screenshot to reproduce.


![image](https://user-images.githubusercontent.com/6299681/39827881-e73db4d8-537e-11e8-8e52-e91bd9a410c5.png)

https://bitcoinacks.com/?flt1_closed_empty=1&desc=1&sort=11&flt0_merged_empty=1
To get there I clicked the Open PRs button and then clicked the Updated table header twice. 

I think updated-desc makes more sense as the default sort than what I currently have (pr number desc), I've made that change https://github.com/PierreRochard/bitcoin-acks/pull/18

**Comment by ryanofsky** [comment]
Thanks, this is working now for me, too. Maybe I just clicked the wrong column before. Sorry for the noise!
