### ISSUE TITLE
Concept NACK shows up as ACK?

### ISSUE THREAD

**Issue by sdaftuar** [PierreRochard/bitcoin-acks#19]
I noticed that MarcoFalke had concept nack'ed PR bitcoin/bitcoin#12360, but he showed up in the ACK column.

**Comment by sdaftuar** [comment]
Never mind! I was reading this wrong...

**Comment by PierreRochard** [comment]
I thought about splitting them up by column but decided against to keep the width of the page reasonable. I’ll rename the column “Reviews” because the current “ACKs” is indeed confusing
