### ISSUE TITLE
Show Concept ACK

### ISSUE THREAD

**Issue by jonasschnelli** [PierreRochard/bitcoin-acks#21]
Have a column for Concept ACK | utACK | Tested ACK...

**Comment by PierreRochard** [comment]
I'm going to give this one some thought, I initially made it all one column to minimize the width of the table but I think you're right that it'd be helpful to separate them out

**Comment by PierreRochard** [comment]
Here's where I'm at: separate column for each ack type, a total "reviews" column, and the ability to search for "all the reviews from X user". Let me know if that fits your vision @jonasschnelli !

![image](https://user-images.githubusercontent.com/6299681/40881707-a1b2dbc0-669b-11e8-804c-6a9aea7fa813.png)

**Comment by jonasschnelli** [comment]
Nice!
List the sum of the amount of tACKs/Concept ACKs, etc. below the user list?

Like
```
# Concept ACKs
- User A
- User B
- User C
Total: 3
```

**Comment by PierreRochard** [comment]
Good idea, I've added it for ones with >= 3 

![image](https://user-images.githubusercontent.com/6299681/40887345-84cb5f58-6715-11e8-969e-78385e5f3afb.png)

**Comment by PierreRochard** [comment]
This is deployed now!
