### ISSUE TITLE
Hide closed and merged PRs?

### ISSUE THREAD

**Issue by laanwj** [PierreRochard/bitcoin-acks#40]
As I use bitcoinacks to find things to merge, one of the most common things I want to do is hide PRs that:
- Are already merged
- Are closed
- Are currently unmergeable (but this is less important)

It's possible to do this with the current filtering, but I keep having to set it up time after time, it would be useful to have stored queries or such, I dunno.

**Comment by laanwj** [comment]
Oh never mind, there is an "Open PRs" button now which seems to pretty much what I want? Never saw it before. Thanks ✨

**Comment by PierreRochard** [comment]
Glad you found that button! You can also bookmark the site with your favorite filters applied, as the filters are stored in the URL
