### ISSUE TITLE
Number of columns, table is becoming too wide

### ISSUE THREAD

**Issue by laanwj** [PierreRochard/bitcoin-acks#51]
The table is becoming too wide. A good thing about an overview site is when it provides an overview at one glance.

Splitting the different types of ACKs into different columns (#44) is a nice idea, but it makes it hard to browse the list here without horizontal scrolling. I could distinguish them based on color quite well.

**Comment by PierreRochard** [comment]
I wanted to try out the change based on feedback from https://github.com/PierreRochard/bitcoin-acks/issues/21
While it was fine on my widescreen 4k desktop monitor, the horizontal scrolling is a problem on my laptop, so I'm going to change it back.

Longer term, it would be easy to have a separate tab for the "wide view": https://github.com/PierreRochard/bitcoin-acks/issues/53

**Comment by laanwj** [comment]
Yeah I'd imagine it's better on a large 4k monitor - making it configurable would make sense.
(I'm currently using a 1080p laptop with fairly large font size so things become unwieldy quick)

**Comment by PierreRochard** [comment]
This is deployed now

**Comment by laanwj** [comment]
Thank you!
