### ISSUE TITLE
Script and tools label is unreadable

### ISSUE THREAD

**Issue by kaplanmaxe** [PierreRochard/bitcoin-acks#59]
Awesome project!

See attached screenshot. The label `Scripts and tools` is unreadable

![screenshot_2018-06-07_00-00-19](https://user-images.githubusercontent.com/3860450/41077677-1568d3ce-69e6-11e8-8c27-e7691e2f343a.png)

**Comment by PierreRochard** [comment]
Thanks for pointing this out! I'm automatically taking the github colors but I see a way I can automatically darken the tags, will address soon!
