### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Warrows** [PierreRochard/bitcoin-acks#72]
Hi there, awesome work. But there seems to be no license or copyright specified on this project. Would you care to add one, so we can know under which conditions we can use it?

**Comment by PierreRochard** [comment]
Sure, what license should it be? BSD? I really don’t care

**Comment by Warrows** [comment]
I think MIT would be good. 2-clauses BSD is nice too. Plenty of choices.

**Comment by PierreRochard** [comment]
Done, thanks for the suggestion
