### ISSUE TITLE
Non-stale utACK shows as Stale utACK

### ISSUE THREAD

**Issue by ken2812221** [PierreRochard/bitcoin-acks#76]
In bitcoin/bitcoin#10973. I reviewed the latest commit e44e639558b1084f14a97847592616c3df9fff38 and typed it in the comment. It should show as utACK on bitcoinacks.com, however it shows stale ack.

**Comment by ken2812221** [comment]
Github sort commits by time order, not by commit order. You may should get `head.sha` to get real commit head.

**Comment by PierreRochard** [comment]
Ah that makes sense, thanks for explaining @ken2812221, I'll fix asap

**Comment by PierreRochard** [comment]
Will deploy the fix later today
