### ISSUE TITLE
Author name not shown in detail view

### ISSUE THREAD

**Issue by fanquake** [PierreRochard/bitcoin-acks#8]
Open any PR into the detail view, i.e https://bitcoinacks.com/details/?url=%2F&id=MDExOlB1bGxSZXF1ZXN0MTg1MzA0NzUx

The "Author" will be displayed as ```<bitcoin_acks.models.users.Users object at ...>```

**Comment by PierreRochard** [comment]
Thanks for pointing this out! I've fixed the problem. 

I also took the liberty of making the details view a modal. I then noticed that this means you can't share the URL anymore, but my opinion is that bitcoinacks is about finding pull requests and then sharing the github link. If you see it differently I'm happy to remove the modal, it's just a boolean flag!
