### ISSUE TITLE
GitHub data not up to date

### ISSUE THREAD

**Issue by guggero** [PierreRochard/bitcoin-acks#98]
It looks to me like the most recent PR that can be found on bitcoinacks.com currently is `#20030` (which is about 5 days old) while on GitHub the newest PR is `#20074`. 

Is it possible that since the changes in b037d7f the CLI data update doesn't work anymore?

**Comment by guggero** [comment]
I debugged this a bit locally. It looks like a478bf22bfc2f60940cbb06791f14ca2f80812d9 broke the PR update mechanism.
Even though `data-cron` calls `src/bitcoin_acks/github_data/pull_requests_data.py`, that file no longer has a main body. But when changing that call to `src/cli.py -u true`, I get "GitHub is already being polled".

**Comment by PierreRochard** [comment]
Fixed
